CREATE SEQUENCE customer_seq
  START WITH 1001
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE branch_seq
  START WITH 101
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE account_seq
  START WITH 10001
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE employee_seq
  START WITH 10001
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE audittrail_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE; 
  
